### PR TITLE
added sending verification email

### PR DESCRIPTION
**Pull request by dibavosta**
Added functionality of sending verification email to make sure the correct email was entered. From now on, we may only try the program with our own emails as there will be emails sent.

### CODE REVIEW

**Comment by hjkim17** [comment]
I think again and I think that we don't need verification field in the database. What about we just check firebaseAuth.getCurrentUser().isEmailVerified() and pass if it is true?

**Comment by hjkim17** [comment]
If you can use firebaseAuth.getCurrentUser().isEmailVerified(), I think it is redundant that we also have verified field in database.

**Comment by dibavosta** [comment]
I understand what you mean, I was also thinking about that and changed it but then changed it back because I thought it's easier for us to see whether a user is verified using the db, since it isn't really obvious from the authentication page on firebase, if you understand what I mean. If we have it in the db, we can easily manually check if a user has verified their email or not, and if a user has not verified it for say 2 months, we delete the user's data. Without this field, I don't know how we would be able to see this without running a script of some kind. But if we don't want to be able to do this we can definitely remove it.

**Comment by hjkim17** [comment]
I think it is okay to have the field, but in that case we should make sure that there's no wrong code that makes the field inconsistent with firebaseAuth.getCurrentUser().isEmailVerified().

**Comment by dibavosta** [comment]
The code should be consistent. Can I merge this and the other pull request to the master branch after one of you have reviewed the code❓

**Comment by hjkim17** [comment]
Yes, I think it is okay to merge two pull requests. Since I checked email verification works well.

**Pull request merged**
